//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mail {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VoteRequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VoteRequest() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mail.VoteRequest", typeof(VoteRequest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] PhMonteBelloLogo {
            get {
                object obj = ResourceManager.GetObject("PhMonteBelloLogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a phmontebellologo.
        /// </summary>
        public static string PhMonteBelloLogoCid {
            get {
                return ResourceManager.GetString("PhMonteBelloLogoCid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Asamblea de Propietarios - P.H. Monte Bello&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: &apos;Arial&apos;, sans-serif;
        ///            background-color: #f4f4f4;
        ///            margin: 0;
        ///            padding: 20px;
        ///            text-align: center;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///      [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string VoteRequestAcknowledgmentBodyHtml {
            get {
                return ResourceManager.GetString("VoteRequestAcknowledgmentBodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Asamblea de Propietarios - P.H. Monte Bello&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: &apos;Arial&apos;, sans-serif;
        ///            background-color: #f4f4f4;
        ///            margin: 0;
        ///            padding: 20px;
        ///            text-align: center;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///      [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string VoteRequestAcknowledgmentResultBodyHtml {
            get {
                return ResourceManager.GetString("VoteRequestAcknowledgmentResultBodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados - Votación - Asamblea de Propietarios del P.H. Monte Bello.
        /// </summary>
        public static string VoteRequestAcknowledgmentResultSubject {
            get {
                return ResourceManager.GetString("VoteRequestAcknowledgmentResultSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibo de Acuse - Votación - Asamblea de Propietarios del P.H. Monte Bello.
        /// </summary>
        public static string VoteRequestAcknowledgmentSubject {
            get {
                return ResourceManager.GetString("VoteRequestAcknowledgmentSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Asamblea de Propietarios - P.H. Monte Bello&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: &apos;Arial&apos;, sans-serif;
        ///            background-color: #f4f4f4;
        ///            margin: 0;
        ///            padding: 20px;
        ///            text-align: center;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///      [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string VoteRequestBodyHtml {
            get {
                return ResourceManager.GetString("VoteRequestBodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Asamblea de Propietarios - P.H. Monte Bello&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: &apos;Arial&apos;, sans-serif;
        ///            background-color: #f4f4f4;
        ///            margin: 0;
        ///            padding: 20px;
        ///            text-align: center;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///      [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string VoteRequestQuorumNewOwnerBodyHtml {
            get {
                return ResourceManager.GetString("VoteRequestQuorumNewOwnerBodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quorum Reglamentario - Asamblea de Propietarios del P.H. Monte Bello.
        /// </summary>
        public static string VoteRequestQuorumNewOwnerSubject {
            get {
                return ResourceManager.GetString("VoteRequestQuorumNewOwnerSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Votación - Asamblea de Propietarios del P.H. Monte Bello.
        /// </summary>
        public static string VoteRequestSubject {
            get {
                return ResourceManager.GetString("VoteRequestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a votingquorumexcellcid.
        /// </summary>
        public static string VotingQuorumExcellCid {
            get {
                return ResourceManager.GetString("VotingQuorumExcellCid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a votingresultexcellcid.
        /// </summary>
        public static string VotingResultExcellCid {
            get {
                return ResourceManager.GetString("VotingResultExcellCid", resourceCulture);
            }
        }
    }
}
